src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        options:
        [
            'unsigned' => true,
        ]
    )]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $sectionTitle = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'sections')]
    private Collection $articles;

    #[ORM\Column(length: 105, unique: true)]
    private ?string $section_slug = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $section_detail = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSectionTitle(): ?string
    {
        return $this->sectionTitle;
    }

    public function setSectionTitle(string $sectionTitle): static
    {
        $this->sectionTitle = $sectionTitle;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addSection($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeSection($this);
        }

        return $this;
    }

    public function getSectionSlug(): ?string
    {
        return $this->section_slug;
    }

    public function setSectionSlug(string $section_slug): static
    {
        $this->section_slug = $section_slug;

        return $this;
    }

    public function getSectionDetail(): ?string
    {
        return $this->section_detail;
    }

    public function setSectionDetail(?string $section_detail): static
    {
        $this->section_detail = $section_detail;

        return $this;
    }
}

src/Controller/CrudSectionController.php
<?php

namespace App\Controller;

use App\Entity\Section;
use App\Form\SectionType;
use App\Repository\SectionRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/crud/section')]
final class CrudSectionController extends AbstractController
{
    #[Route(name: 'app_crud_section_index', methods: ['GET'])]
    public function index(SectionRepository $sectionRepository): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()))return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        return $this->render('crud_section/index.html.twig', [
            'sections' => $sectionRepository->findAll(),
            'user' => $user,
        ]);
    }

    #[Route('/new', name: 'app_crud_section_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SectionRepository $sectionRepository): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()))return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        $section = new Section();
        $form = $this->createForm(SectionType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slugify = new Slugify();
            $section->setSectionSlug($slugify->slugify($section->getSectionTitle()));
            $entityManager->persist($section);
            $entityManager->flush();

            return $this->redirectToRoute('app_crud_section_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crud_section/new.html.twig', [
            'sections' => $sectionRepository->findAll(),
            'section' => $section,
            'form' => $form,
            'user' => $user,
        ]);
    }

    #[Route('/{slug}', name: 'app_crud_section_show', methods: ['GET'])]
    public function show(string $slug, SectionRepository $sectionRepository): Response
    {
        $user = $this->getUser();
        $section = $sectionRepository->getSectionBySlug($slug);
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()))return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        return $this->render('crud_section/show.html.twig', [
            'sections' => $sectionRepository->findAll(),
            'section' => $section,
            'user' => $user,
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_crud_section_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, string $slug, EntityManagerInterface $entityManager, SectionRepository $sectionRepository): Response
    {
        $user = $this->getUser();
        $section = $sectionRepository->getSectionBySlug($slug);
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()))return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        $form = $this->createForm(SectionType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slugify = new Slugify();
            $section->setSectionSlug($slugify->slugify($section->getSectionTitle()));
            $entityManager->persist($section);
            $entityManager->flush();

            return $this->redirectToRoute('app_crud_section_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crud_section/edit.html.twig', [
            'sections' => $sectionRepository->findAll(),
            'section' => $section,
            'form' => $form,
            'user' => $user,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_section_delete', methods: ['POST'])]
    public function delete(Request $request, Section $section, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()))return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        if ($this->isCsrfTokenValid('delete'.$section->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($section);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_crud_section_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/crud_section/_delete_form.html.twig
<form method="post" action="{{ path('app_crud_section_delete', {'id': section.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ section.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/crud_section/_form.html.twig
<div class="container">
    {{ form_start(form) }}
        <div class="form-group mb-2">
            {{ form_label(form.sectionTitle, "Titre: ") }}
            <br>
            {{ form_widget(form.sectionTitle, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.sectionTitle) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.sectionDetail, "Description: ") }}
            <br>
            {{ form_widget(form.sectionDetail, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.sectionDetail) }}
        </div>

        <button class="btn btn-primary">{{ button_label|default('Créer') }}</button>
    {{ form_end(form) }}
</div>

templates/crud_section/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Section {{ section.sectionTitle }}{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Modifier Section {{ section.sectionTitle }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Modifier Section</h1>
                {{ include('crud_section/_form.html.twig', {'button_label': 'Modifier'}) }}
                <a href="{{ path('app_crud_section_index') }}">Retour à la liste</a>
                {{ include('crud_section/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_section/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Section CRUD{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1 class="text-center">Section CRUD</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Section CRUD</h1>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Titre</th>
                            <th>Description</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for section in sections %}
                        <tr>
                            <td>{{ section.id }}</td>
                            <td>{{ section.sectionTitle }}</td>
                            <td>{{ section.sectionDetail }}</td>
                            <td>
                                <a href="{{ path('app_crud_section_show', {'slug': section.sectionSlug}) }}">Voir</a>
                                <a href="{{ path('app_crud_section_edit', {'slug': section.sectionSlug}) }}">Modifier</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{{ path('app_crud_section_new') }}">Créer nouveau</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_section/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Section{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Nouvelle Section</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Nouvelle Section</h1>
                {{ include('crud_section/_form.html.twig') }}
                <a href="{{ path('app_crud_section_index') }}">Retour à la liste</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_section/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Section: {{ section.sectionTitle }}{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1 class="text-center">Section: {{ section.sectionTitle }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1><a href="{{ path('section', {slug: section.sectionSlug}) }}">Section</a></h1>

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ section.id }}</td>
                        </tr>
                        <tr>
                            <th>Titre</th>
                            <td>{{ section.sectionTitle }}</td>
                        </tr>
                        <tr>
                        <th>Description</th>
                            <td>{{ section.sectionDetail }}</td>
                        </tr>
                    </tbody>
                </table>

                <a href="{{ path('app_crud_section_index') }}">Retour à la liste</a>

                <a href="{{ path('app_crud_section_edit', {'slug': section.sectionSlug}) }}">Modifier</a>

                {{ include('crud_section/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}