src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        # on veut que l'ID soit 'unsigned'
        options:
        [
            'unsigned' => true,
        ]
    )]
    private ?int $id = null;

    #[ORM\Column(length: 160)]
    private ?string $title = null;

    /**
     * @var Collection<int, Section>
     */
    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'articles')]
    private Collection $sections;


    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'article')]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 162)]
    private ?string $title_slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $text = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: [
        'default' => 'CURRENT_TIMESTAMP'
      ])]
    private ?\DateTimeInterface $article_date_create;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $article_date_posted;

    #[ORM\Column(type: Types::BOOLEAN, options: [
        'default' => '0'
      ])]
    private ?bool $published = null;

    public function __construct()
    {
        $this->article_date_create = new \DateTime();
        $this->sections = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;
        $slugify = new Slugify();
        $this->title_slug = $slugify->slugify($title);

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTitleSlug(): ?string
    {
        return $this->title_slug;
    }

    public function setTitleSlug(string $title_slug): static
    {
        $this->title_slug = $title_slug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getArticleDateCreate(): ?\DateTimeInterface
    {
        return $this->article_date_create;
    }

    public function setArticleDateCreate(\DateTimeInterface $article_date_create): static
    {
        $this->article_date_create = $article_date_create;

        return $this;
    }

    public function getArticleDatePosted(): ?\DateTimeInterface
    {
        return $this->article_date_posted;
    }

    public function setArticleDatePosted(?\DateTimeInterface $article_date_posted): static
    {
        $this->article_date_posted = $article_date_posted;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        options:
        [
            'unsigned' => true,
        ]
    )]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $sectionTitle = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'sections')]
    private Collection $articles;

    #[ORM\Column(length: 105, unique: true)]
    private ?string $section_slug = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $section_detail = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSectionTitle(): ?string
    {
        return $this->sectionTitle;
    }

    public function setSectionTitle(string $sectionTitle): static
    {
        $this->sectionTitle = $sectionTitle;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addSection($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeSection($this);
        }

        return $this;
    }

    public function getSectionSlug(): ?string
    {
        return $this->section_slug;
    }

    public function setSectionSlug(string $section_slug): static
    {
        $this->section_slug = $section_slug;

        return $this;
    }

    public function getSectionDetail(): ?string
    {
        return $this->section_detail;
    }

    public function setSectionDetail(?string $section_detail): static
    {
        $this->section_detail = $section_detail;

        return $this;
    }
}

src/Controller/CrudArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\NewArticleType;
use App\Form\ArticleType;
use App\Form\RedacArticleType;
use App\Repository\ArticleRepository;
use App\Repository\SectionRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/crud/article')]
final class CrudArticleController extends AbstractController
{
    #[Route(name: 'app_crud_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository, SectionRepository $SectionRepository): Response
    {
        $user = $this->getUser();
        if ($user && in_array("ROLE_ADMIN", $user->getRoles())){
            $articles = $articleRepository->findAll();
        }else if ($user && in_array("ROLE_REDAC", $user->getRoles())){
            $articles = $articleRepository->findAllByAuthor($user->getId());
        }else {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }

        $sections = $SectionRepository->findAll();
        return $this->render('crud_article/index.html.twig', [
            'sections' => $sections,
            'articles' => $articles,
            'user' => $user,
        ]);
    }

    #[Route('/new', name: 'app_crud_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SectionRepository $SectionRepository): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()) && !in_array("ROLE_REDAC", $user->getRoles())){
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $article = new Article();
        $form = $this->createForm(NewArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slugify = new Slugify();
            $article->setUser($this->getUser());
            $article->setTitleSlug($slugify->slugify($article->getTitle()));

            $is_going_to_be_published = $form->getData()->getPublished();
            if ($is_going_to_be_published){
                $article->setArticleDatePosted(new \DateTime());
            }

            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
        }

        $sections = $SectionRepository->findAll();
        return $this->render('crud_article/new.html.twig', [
            'sections' => $sections,
            'article' => $article,
            'form' => $form,
            'user' => $user,
        ]);
    }

    #[Route('/{slug}', name: 'app_crud_article_show', methods: ['GET'])]
    public function show(string $slug, ArticleRepository $ArticleRepository, SectionRepository $SectionRepository): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()) && !in_array("ROLE_REDAC", $user->getRoles())){
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $article = $ArticleRepository->getArticleBySlug($slug);
        if (!in_array("ROLE_ADMIN", $user->getRoles()) && $user->getId() != $article->getUser()->getId()){
            return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
        }
        $sections = $SectionRepository->findAll();
        return $this->render('crud_article/show.html.twig', [
            'sections' => $sections,
            'article' => $article,
            'user' => $user,
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_crud_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, string $slug, ArticleRepository $ArticleRepository, EntityManagerInterface $entityManager, SectionRepository $SectionRepository): Response
    {
        $user = $this->getUser();
        // if not user or neither redac nor admin
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()) && !in_array("ROLE_REDAC", $user->getRoles())){
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $article = $ArticleRepository->getArticleBySlug($slug);
        $was_published = $article->getPublished();
        if (!in_array("ROLE_ADMIN", $user->getRoles()) && $user->getId() != $article->getUser()->getId()){
            return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
        }
        if (in_array("ROLE_ADMIN", $user->getRoles())){
            $form = $this->createForm(ArticleType::class, $article);
        }else {
            $form = $this->createForm(RedacArticleType::class, $article);
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $is_going_to_be_published = $form->getData()->getPublished();
            if (!$was_published && $is_going_to_be_published){
                $article->setArticleDatePosted(new \DateTime());
            }else if ($was_published && !$is_going_to_be_published) {
                $article->setArticleDatePosted(null);
            }
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
        }

        $sections = $SectionRepository->findAll();
        return $this->render('crud_article/edit.html.twig', [
            'article' => $article,
            'sections' => $sections,
            'form' => $form,
            'user' => $user,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if (!$user || !in_array("ROLE_ADMIN", $user->getRoles()) && !in_array("ROLE_REDAC", $user->getRoles())){
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        if (!in_array("ROLE_ADMIN", $user->getRoles()) && $user->getId() != $article->getUser()->getId()){
            return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
        }
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_crud_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/crud_article/_delete_form.html.twig
<form method="post" action="{{ path('app_crud_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/crud_article/_form.html.twig
<div class="container">
    {{ form_start(form) }}
        <div class="form-group mb-2">
            {{ form_label(form.title, "Titre: ") }}
            <br>
            {{ form_widget(form.title, {'attr': {'class': 'mt-1', 'placeholder': 'Titre'}}) }}
            {{ form_errors(form.title) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.user, "Utilisateur: ") }}
            <br>
            {{ form_widget(form.user, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.user) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.text, "Text: ") }}
            <br>
            {{ form_widget(form.text, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.text) }}
        </div>
        <div class="form-group mb-2">
            {{ form_widget(form.published, {'attr': {'class': 'mt-1'}}) }}
            {{ form_label(form.published, "Publié") }}
            {{ form_errors(form.published) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.sections, "Sections: ") }}
            <br>
            {{ form_widget(form.sections, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.sections) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.articleDateCreate, "Date de création: ") }}
            <br>
            {{ form_widget(form.articleDateCreate, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.articleDateCreate) }}
        </div>
        <button class="btn btn-primary">{{ button_label|default('Envoyer') }}</button>
    {{ form_end(form) }}
</div>

templates/crud_article/_new_form.html.twig
<div class="container">
    {{ form_start(form) }}
        <div class="form-group mb-2">
            {{ form_label(form.title, "Titre: ") }}
            <br>
            {{ form_widget(form.title, {'attr': {'class': 'mt-1', 'placeholder': 'Titre'}}) }}
            {{ form_errors(form.title) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.text, "Text: ") }}
            <br>
            {{ form_widget(form.text, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.text) }}
        </div>
        <div class="form-group mb-2">
            {{ form_widget(form.published, {'attr': {'class': 'mt-1'}}) }}
            {{ form_label(form.published, "Publié") }}
            {{ form_errors(form.published) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.sections, "Sections: ") }}
            <br>
            {{ form_widget(form.sections, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.sections) }}
        </div>
        <button class="btn btn-primary">{{ button_label|default('Envoyer') }}</button>
    {{ form_end(form) }}
</div>

templates/crud_article/_redac_form.html.twig
<div class="container">
    {{ form_start(form) }}
        <div class="form-group mb-2">
            {{ form_label(form.title, "Titre: ") }}
            <br>
            {{ form_widget(form.title, {'attr': {'class': 'mt-1', 'placeholder': 'Titre'}}) }}
            {{ form_errors(form.title) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.text, "Text: ") }}
            <br>
            {{ form_widget(form.text, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.text) }}
        </div>
        <div class="form-group mb-2">
            {{ form_widget(form.published, {'attr': {'class': 'mt-1'}}) }}
            {{ form_label(form.published, "Publié") }}
            {{ form_errors(form.published) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.sections, "Sections: ") }}
            <br>
            {{ form_widget(form.sections, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.sections) }}
        </div>
        <div class="form-group mb-2">
            {{ form_label(form.articleDateCreate, "Date de création: ") }}
            <br>
            {{ form_widget(form.articleDateCreate, {'attr': {'class': 'mt-1'}}) }}
            {{ form_errors(form.articleDateCreate) }}
        </div>
        <button class="btn btn-primary">{{ button_label|default('Envoyer') }}</button>
    {{ form_end(form) }}
</div>

templates/crud_article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Article{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Modifier Le Article</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="container mt-3">
                    <h1>Modifier Le Article</h1>
                </div>
                {% if "ROLE_ADMIN" in user.roles %}
                {{ include('crud_article/_form.html.twig', {'button_label': 'Modifier'}) }}
                {% else %}
                {{ include('crud_article/_redac_form.html.twig', {'button_label': 'Modifier'}) }}
                {% endif %}
                <div class="container mt-3">
                    <a href="{{ path('app_crud_article_index') }}">Retour à la liste</a>
                    {{ include('crud_article/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article CRUD{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Article CRUD</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Article CRUD</h1>
                <div class="text-end"><a href="{{ path('app_crud_article_new') }}">Créer nouveau</a></div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Titre</th>
                            <th>Auteur</th>
                            <th>Date de création</th>
                            <th>Publié</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{ article.id }}</td>
                            <td>{{ article.title }}</td>
                            <td><a href="{{ path('app_author', {uniqid: article.user.uniqid}) }}">{{ article.user.fullname }}</a></td>
                            <td>{{ article.articleDateCreate ? article.articleDateCreate|date('d/m/Y H:i:s') : '' }}</td>
                            <td>{{ article.published ? 'Oui' : 'Non' }}</td>
                            <td>
                                <a href="{{ path('app_crud_article_show', {'slug': article.titleSlug}) }}">Voir</a>
                                <a href="{{ path('app_crud_article_edit', {'slug': article.titleSlug}) }}">Modifier</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">Aucune donné trouvée</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{{ path('app_crud_article_new') }}">Créer nouveau</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Article{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Créer un nouveau article</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="container mt-3">
                    <h1>Créer un nouveau article</h1>
                </div>

                {{ include('crud_article/_new_form.html.twig') }}

                <div class="container mt-3">
                    <a href="{{ path('app_crud_article_index') }}">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/crud_article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article Voir{% endblock %}

{% block body %}
    <!-- Page Header-->
    <header class="masthead">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Article Voir</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1><a href="{{ path('app_article', {slug: article.titleSlug}) }}">Article</a></h1>

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ article.id }}</td>
                        </tr>
                        <tr>
                            <th>Autheur</th>
                            <td><a href="{{ path('app_author', {uniqid: article.user.uniqid}) }}">{{ article.user.username }} | {{ article.user.fullname }}</a></td>
                        </tr>
                        <tr>
                            <th>Titre</th>
                            <td>{{ article.title }}</td>
                        </tr>
                        <tr>
                            <th>text</th>
                            <td>{{ article.text }}</td>
                        </tr>
                        <tr>
                            <th>Sections</th>
                            <td>
                                {% for section in article.sections %}
                                <a href="{{ path('section', {slug: section.sectionSlug}) }}">{{ section.sectionTitle }}</a>{% if not loop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th>Date de création</th>
                            <td>{{ article.articleDateCreate ? article.articleDateCreate|date('d/m/Y H:i:s') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Date de publication</th>
                            <td>{{ article.articleDatePosted ? article.articleDatePosted|date('d/m/Y H:i:s') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Publié</th>
                            <td>{{ article.published ? 'Oui' : 'Non' }}</td>
                        </tr>
                    </tbody>
                </table>

                <a href="{{ path('app_crud_article_index') }}">Retour à la liste</a>

                <a href="{{ path('app_crud_article_edit', {'slug': article.titleSlug}) }}">Modifier</a>

                {{ include('crud_article/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}